# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for Gradle
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "/cdaschema"
      - "/data-ingestion-service"
      - "/data-processing-service"
      - "/deduplication"
      - "/hl7-parser" 
      - "/karatetest" 
      - "/phdc-xsd-jaxb"
      - "/srte-data-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories:
      - "/containers/db"
      - "/containers/nbs-classic"
      - "/data-ingestion-service"
      - "/data-processing-service"
      - "/deduplication"
      - "/srte-data-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2

  # Enable version updates for Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2